//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

/* eslint-disable */
/* jshint ignore: start */

(function(module, require, exports)
{
    const Ice = require("ice").Ice;
    const _ModuleRegistry = Ice._ModuleRegistry;
    const Slice = Ice.Slice;

    let Chat = _ModuleRegistry.module("Chat");

    Chat.Msg = class
    {
        constructor(id = "", sender = "", recipient = "", text = "", timestamp = new Ice.Long(0, 0))
        {
            this.id = id;
            this.sender = sender;
            this.recipient = recipient;
            this.text = text;
            this.timestamp = timestamp;
        }

        _write(ostr)
        {
            ostr.writeString(this.id);
            ostr.writeString(this.sender);
            ostr.writeString(this.recipient);
            ostr.writeString(this.text);
            ostr.writeLong(this.timestamp);
        }

        _read(istr)
        {
            this.id = istr.readString();
            this.sender = istr.readString();
            this.recipient = istr.readString();
            this.text = istr.readString();
            this.timestamp = istr.readLong();
        }

        static get minWireSize()
        {
            return  12;
        }
    };

    Slice.defineStruct(Chat.Msg, true, true);

    Slice.defineSequence(Chat, "MsgSeqHelper", "Chat.Msg", false);

    const iceC_Chat_ClientCallback_ids = [
        "::Chat::ClientCallback",
        "::Ice::Object"
    ];

    Chat.ClientCallback = class extends Ice.Object
    {
    };

    Chat.ClientCallbackPrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(Chat.ClientCallback, Chat.ClientCallbackPrx, iceC_Chat_ClientCallback_ids, 0,
    {
        "onNewMessage": [, , , , , [[Chat.Msg]], , , , ],
        "onUserJoined": [, , , , , [[7]], , , , ],
        "onUserLeft": [, , , , , [[7]], , , , ]
    });

    const iceC_Chat_Service_ids = [
        "::Chat::Service",
        "::Ice::Object"
    ];

    Chat.Service = class extends Ice.Object
    {
    };

    Chat.ServicePrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(Chat.Service, Chat.ServicePrx, iceC_Chat_Service_ids, 0,
    {
        "login": [, , , , , [[7], ["Chat.ClientCallbackPrx"]], , , , ],
        "sendText": [, , , , , [[7], [7], [7]], , , , ],
        "createGroup": [, , , , , [[7], [7]], , , , ],
        "joinGroup": [, , , , , [[7], [7]], , , , ],
        "getHistory": [, , , , ["Chat.MsgSeqHelper"], [[7], [3]], , , , ]
    });
    exports.Chat = Chat;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self.Ice._require : window.Ice._require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self : window));
